{
 "title": "ActiveMQ",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "release", "label": "release", "query": "label_values(release)" }
  ]
 },
 "panels": [
  { "title": "ActiveMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds)*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jvm_info{}" }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "ActiveMQ Current Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "activemq_connections", "legendFormat": "Current Connections" },
    { "expr": "activemq_connections_total", "legendFormat": "Total Connections" }
   ]
  },
  {
   "title": "Enqueue / Dequeued ",
   "type": "stat",
   "description": "Number of messages that have been sent to the broker and Number of messages that have been acknowledged on the broker.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "activemq_enqueue_total", "legendFormat": "Enqueued Total" },
    { "expr": "activemq_dequeue_total", "legendFormat": "Dequeued Total" }
   ]
  },
  {
   "title": "Consumer/ Producer",
   "type": "stat",
   "description": "Number of message consumers subscribed to destinations on the broker and Number of message producers active on destinations on the broker.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "activemq_consumer_total", "legendFormat": "Consumer" },
    { "expr": "activemq_producer_total", "legendFormat": "Producer" }
   ]
  },
  {
   "title": "Pending messages",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "activemq_queue_queue_size{destination=~\"realtime-events|General|MreMicroservice|CommunicationServer|RoutingEngine|error_queue|external|facebook|reporting|smpp|viber|sms|whatsapp\"} ",
     "legendFormat": " {{destination}}"
    }
   ]
  },
  {
   "title": "Number of Consumers",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "activemq_queue_consumer_count{destination=~\"realtime-events|General|MreMicroservice|CommunicationServer|RoutingEngine|error_queue|external|facebook|reporting|smpp|viber|sms|whatsapp\"}",
     "legendFormat": " {{destination}}"
    }
   ]
  },
  {
   "title": "Queue enqueue Count",
   "type": "bargauge",
   "description": " Number of messages that have been sent to the destination. ",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "activemq_queue_enqueue_count{destination=~\"realtime-events|General|MreMicroservice|CommunicationServer|RoutingEngine|error_queue|external|facebook|reporting|smpp|viber|sms|whatsapp\"}",
     "legendFormat": " {{destination}}"
    }
   ]
  },
  {
   "title": "Queue Dequeue Count",
   "type": "bargauge",
   "description": " Number of messages that has been acknowledged (and removed) from the destination. ",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "activemq_queue_dequeue_count{destination=~\"realtime-events|General|MreMicroservice|CommunicationServer|RoutingEngine|error_queue|external|facebook|reporting|smpp|viber|sms|whatsapp\"} ",
     "legendFormat": " {{destination}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current",
     "legendFormat": "JVM current threads  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon",
     "legendFormat": "JVM daemon threads {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked",
     "legendFormat": "JVM deadlocked threads  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[5m])",
     "legendFormat": "{{gc}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded",
     "legendFormat": "loaded  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory pool [JIT code cache]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"JIT code cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"JIT code cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"JIT code cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [JIT Data Cache]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"JIT data cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"JIT data cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"JIT data cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [Class Storage]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"class storage\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"class storage\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"class storage\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool miscellaneous non-heap storage]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"miscellaneous non-heap storage\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"miscellaneous non-heap storage\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"miscellaneous non-heap storage\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory Pool [Nursery Allocate]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max {job=~\"activemq\", pool=~\"nursery-allocate\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used {job=~\"activemq\", pool=~\"nursery-allocate\"}",
     "legendFormat": "Used "
    },
    {
     "expr": "jvm_memory_pool_bytes_committed {job=~\"activemq\", pool=~\"nursery-allocate\"}",
     "legendFormat": "Committed  "
    }
   ]
  },
  {
   "title": "Memory Pool [nursery survivor]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max {job=~\"activemq\", pool=~\"nursery-survivor\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used {job=~\"activemq\", pool=~\"nursery-survivor\"}",
     "legendFormat": "Used "
    },
    {
     "expr": "jvm_memory_pool_bytes_committed {job=~\"activemq\", pool=~\"nursery-survivor\"}",
     "legendFormat": "Committed  "
    }
   ]
  },
  {
   "title": "Memory Pool [tenured LOA]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max {job=~\"activemq\", pool=~\"tenured-LOA\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used {job=~\"activemq\", pool=~\"tenured-LOA\"}",
     "legendFormat": "Used "
    },
    {
     "expr": "jvm_memory_pool_bytes_committed {job=~\"activemq\", pool=~\"tenured-LOA\"}",
     "legendFormat": "Committed  "
    }
   ]
  },
  {
   "title": "Memory Pool [tenured SOA]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max {job=~\"activemq\", pool=~\"tenured-SOA\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used {job=~\"activemq\", pool=~\"tenured-SOA\"}",
     "legendFormat": "Used "
    },
    {
     "expr": "jvm_memory_pool_bytes_committed {job=~\"activemq\", pool=~\"tenured-SOA\"}",
     "legendFormat": "Committed  "
    }
   ]
  }
 ]
}